### ISSUE TITLE
Crash upon opening a door with a key

### ISSUE THREAD

**Issue by QuasiStellar** [QuasiStellar/shattered-pixel-dungeon-remastered#11]
```
java.lang.IllegalArgumentException: remaining() < size < needed
        at android.opengl.GLES20.glBufferSubData(Native Method)
        at com.badlogic.gdx.backends.android.AndroidGL20.glBufferSubData(AndroidGL20.java:84)
        at com.watabou.glwrap.VertexDataset.updateGlData(VertexDataset.kt:54)
        at com.watabou.noosa.Script.drawQuadSet(Script.kt:110)
        at com.shatteredpixel.shatteredpixeldungeon.ui.KeyDisplay.draw(KeyDisplay.java:119)
        at com.watabou.noosa.Group.draw(Group.kt:58)
        at com.watabou.noosa.Group.draw(Group.kt:58)
        at com.watabou.noosa.Group.draw(Group.kt:58)
        at com.shatteredpixel.shatteredpixeldungeon.scenes.PixelScene.draw(PixelScene.java:208)
        at com.watabou.noosa.Game.draw(Game.java:248)
        at com.watabou.noosa.Game.render(Game.java:170)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)```

**Comment by QuasiStellar** [comment]
Caused by https://github.com/QuasiStellar/shattered-pixel-dungeon-remastered/commit/b89d8527a404712b5de3b9ed6c9a86c0c026b54e

**Comment by QuasiStellar** [comment]
Fixed in https://github.com/QuasiStellar/shattered-pixel-dungeon-remastered/commit/f3c02c4a5f4bb11546dc1392ba4d2c37fa3cb284
