### ISSUE TITLE
Crash when hp drops below 50%

### ISSUE THREAD

**Issue by QuasiStellar** [QuasiStellar/shattered-pixel-dungeon-remastered#6]
```
E/AndroidRuntime: FATAL EXCEPTION: SHPD Render Thread
    Process: com.shatteredpixel.shatteredpixeldungeon.indev, PID: 6354
    java.lang.IllegalArgumentException: remaining() < size < needed
        at android.opengl.GLES20.glBufferSubData(Native Method)
        at com.badlogic.gdx.backends.android.AndroidGL20.glBufferSubData(AndroidGL20.java:84)
        at com.watabou.glwrap.VertexDataset.updateGlData(VertexDataset.kt:54)
        at com.watabou.noosa.Script.drawQuadSet(Script.kt:110)
        at com.watabou.noosa.BitmapText.draw(BitmapText.java:94)
        at com.watabou.noosa.Group.draw(Group.kt:58)
        at com.watabou.noosa.Group.draw(Group.kt:58)
        at com.shatteredpixel.shatteredpixeldungeon.scenes.PixelScene.draw(PixelScene.java:217)
        at com.watabou.noosa.Game.draw(Game.java:248)
        at com.watabou.noosa.Game.render(Game.java:170)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
I/Process: Sending signal. PID: 6354 SIG: 9
```

**Comment by QuasiStellar** [comment]
Fixed in https://github.com/QuasiStellar/shattered-pixel-dungeon-remastered/commit/f3c02c4a5f4bb11546dc1392ba4d2c37fa3cb284
